### PR TITLE
Rework deploy script for PCF, trim static site memory to 64MB, fix minor issues

### LINKED ISSUE #70: PWS deployment: bring down the memory footprint of the deployed `web` app
When deploying to CF, the API uses 256MB memory. However, the web app uses the default memory, which is 1GB on PWS. We can probably trim this down to 64MB or even 32MB (currently, when there are no requests, it uses 13MB of memory).

Thoughts ?

### PR DESCRIPTION
**Pull request by Kehrlann**
Quite a "big" PR, tackling :
1. Add react-hot-loader dependency to package.json - the front-end wouldn't build otherwise.
2. Rework the CF deploy script, as discussed in #69. We now use one `deploy.sh` script for both PCF and PWS, as the script itself is the same for both environments. Tested it using the PCF folder, and fixed a minor issue in `config.js`
3. Fix #70 : the static site is now served with 64MB of memory. 32MB should be enough, but, in doubt, 64MB is a good start.

### CODE REVIEW

File: deployment/pcf/config/config.js [hunk 1]
```diff
@@ -6,7 +6,7 @@ window.Retro = {
     "stylesheets": ["application.css"],
     "useRevManifest": true,
     "api_base_url": "https://{{api-app-name}}.{{pcf-url}}",
-    "websocket_url": "wss://{{api-app-name}}.{{pcf-url}}:443/cable",
+    "websocket_url": "wss://{{api-app-name}}.{{pcf-url}}:4443/cable",
```
Comment (seadowg) [inline deployment/pcf/config/config.js]: This actually isn't a mistake. PWS runs (secure) websockets on 4443 but most PCF installations will run it on the standard 443. Could you revert this please?

Comment (Kehrlann) [reply deployment/pcf/config/config.js]: Ah, good catch, thanks. I deployed it to PWS, couldn't get my hands on a regular PCF. Reverted.

**Comment by seadowg** [comment]
Thanks! 🙌
